Description:
  Slug: MibS
  ShortName: MibS
  LongName: Mixed Integer Bilevel Solver
  ShortDescription: Solver for mixed integer bilevel optimization problems.
  LongDescription: |2
    MibS is a solver for mixed integer bilevel optimization problems.
  Manager: Ted Ralphs, ted at lehigh dot edu
  Homepage: https://github.com/coin-or/MibS
  License: Eclipse Public License 2.0
  LicenseURL: http://www.opensource.org/licenses/EPL-2.0
  Zenodo: 39053653
  IncludedIn: 
    Package: MibS
  Language:
    - C++
  Categories: 
    - Interfaces
    - Optimization bilevel
    - Optimization deterministic linear discrete
  PaperCite: https://doi.org/10.1007/s12532-020-00183-6
Dependencies:
  - Description: ThirdParty wrapper for building Mumps
    URL: https://github.com/coin-or-tools/ThirdParty-Mumps
    Version: 3.0
    Required: Optional
  - Description: Sample data files
    URL: https://github.com/coin-or-tools/Data-Sample
    Version: 1.2
    Required: Required
  - Description: Miplib3 data files
    URL: https://github.com/coin-or-tools/Data-miplib3
    Version: 1.2
    Required: Required
  - Description: COIN-OR Utilities
    URL: https://github.com/coin-orCoinUtils
    Version: master
    Required: Required
  - Description: Open Solver Interface
    URL: https://github.com/coin=-or/Osi
    Version: master
    Required: Required
  - Description: COIN-OR Linear Programming Solver
    URL: https://github.com/coin-or/Clp
    Version: master
    Required: Required
  - Description: Cut Generation Library
    URL: https://github.com/coin-or/Cgl
    Version: master
    Required: Required
  - Description: Abstract Library for Parallel Search
    URL: https://github.com/coin-or/CHiPPS-ALPS
    Version: 1.6
    Required: Required
  - Description: Branch, Constrain, and Price Framework
    URL: https://github.com/coin-or/CHiPPS-BiCePS
    Version: 0.95
    Required: Required
  - Description: BiCePS Linear Integer Solver
    URL: https://github.com/coin-or/CHiPPS-BLIS
    Version: 0.95
    Required: Required
  - Description: SYMPHONY Mip Solver
    URL: https://github.com/coin-or/SYMPHONY
    Version: master
    Required: Required
  - Description: COIN-OR Branch-and-cut
    URL: https://github.com/coin-or/Cbc
    Version: master
    Required: Required
  - Description: Basic Linear Algebra Subroutines (BLAS)
    URL: http://www.netlib.org/blas
    Required: Recommended
  - Description: Linear Algebra Package (LAPACK)
    URL: http://www.netlib.org/lapack
    Required: Recommended
  - Description: GNU Readline
    Required: Recommended
  - Description: GNU History
    Required: Recommended

DevelopmentStatus: 
  activityStatus: Active
  maturityLevel: 5
  testedPlatforms: 
  - operatingSystem: Linux
    compiler: gcc
  - operatingSystem: Mac OS X
    compiler:
    - gcc
    - clang
  - operatingSystem: Microsoft Windows
    compiler: cl
  - operatingSystem: Microsoft Windows with MSys2
    compiler:
    - gcc
    - cl
    - icl
  - operatingSystem: Microsoft Windows Subsystem for Linux
    compiler:
    - gcc
    - cl
    - icl
